/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConsentDomainUpdate
 */
public class ConsentDomainUpdateTest {
    private final ConsentDomainUpdate model = new ConsentDomainUpdate();

    /**
     * Model tests for ConsentDomainUpdate
     */
    @Test
    public void testConsentDomainUpdate() {
        // TODO: test ConsentDomainUpdate
    }

    /**
     * Test the property 'agreedAt'
     */
    @Test
    public void agreedAtTest() {
        // TODO: test agreedAt
    }

    /**
     * Test the property 'agreedBy'
     */
    @Test
    public void agreedByTest() {
        // TODO: test agreedBy
    }

    /**
     * Test the property 'agreementKeys'
     */
    @Test
    public void agreementKeysTest() {
        // TODO: test agreementKeys
    }

}
