/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for ConsentRenew
 */
public class ConsentRenewTest {
    private final ConsentRenew model = new ConsentRenew();

    /**
     * Model tests for ConsentRenew
     */
    @Test
    public void testConsentRenew() {
        // TODO: test ConsentRenew
    }

    /**
     * Test the property 'agreedAt'
     */
    @Test
    public void agreedAtTest() {
        // TODO: test agreedAt
    }

    /**
     * Test the property 'agreedBy'
     */
    @Test
    public void agreedByTest() {
        // TODO: test agreedBy
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'price'
     */
    @Test
    public void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'registryPremiumPricing'
     */
    @Test
    public void registryPremiumPricingTest() {
        // TODO: test registryPremiumPricing
    }

}
