/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ContactDomainCreate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DomainContactsCreateV2
 */
public class DomainContactsCreateV2Test {
    private final DomainContactsCreateV2 model = new DomainContactsCreateV2();

    /**
     * Model tests for DomainContactsCreateV2
     */
    @Test
    public void testDomainContactsCreateV2() {
        // TODO: test DomainContactsCreateV2
    }

    /**
     * Test the property 'admin'
     */
    @Test
    public void adminTest() {
        // TODO: test admin
    }

    /**
     * Test the property 'adminId'
     */
    @Test
    public void adminIdTest() {
        // TODO: test adminId
    }

    /**
     * Test the property 'billing'
     */
    @Test
    public void billingTest() {
        // TODO: test billing
    }

    /**
     * Test the property 'billingId'
     */
    @Test
    public void billingIdTest() {
        // TODO: test billingId
    }

    /**
     * Test the property 'registrant'
     */
    @Test
    public void registrantTest() {
        // TODO: test registrant
    }

    /**
     * Test the property 'registrantId'
     */
    @Test
    public void registrantIdTest() {
        // TODO: test registrantId
    }

    /**
     * Test the property 'tech'
     */
    @Test
    public void techTest() {
        // TODO: test tech
    }

    /**
     * Test the property 'techId'
     */
    @Test
    public void techIdTest() {
        // TODO: test techId
    }

}
