/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Contact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DomainSummary
 */
public class DomainSummaryTest {
    private final DomainSummary model = new DomainSummary();

    /**
     * Model tests for DomainSummary
     */
    @Test
    public void testDomainSummary() {
        // TODO: test DomainSummary
    }

    /**
     * Test the property 'authCode'
     */
    @Test
    public void authCodeTest() {
        // TODO: test authCode
    }

    /**
     * Test the property 'contactAdmin'
     */
    @Test
    public void contactAdminTest() {
        // TODO: test contactAdmin
    }

    /**
     * Test the property 'contactBilling'
     */
    @Test
    public void contactBillingTest() {
        // TODO: test contactBilling
    }

    /**
     * Test the property 'contactRegistrant'
     */
    @Test
    public void contactRegistrantTest() {
        // TODO: test contactRegistrant
    }

    /**
     * Test the property 'contactTech'
     */
    @Test
    public void contactTechTest() {
        // TODO: test contactTech
    }

    /**
     * Test the property 'createdAt'
     */
    @Test
    public void createdAtTest() {
        // TODO: test createdAt
    }

    /**
     * Test the property 'deletedAt'
     */
    @Test
    public void deletedAtTest() {
        // TODO: test deletedAt
    }

    /**
     * Test the property 'domain'
     */
    @Test
    public void domainTest() {
        // TODO: test domain
    }

    /**
     * Test the property 'domainId'
     */
    @Test
    public void domainIdTest() {
        // TODO: test domainId
    }

    /**
     * Test the property 'expirationProtected'
     */
    @Test
    public void expirationProtectedTest() {
        // TODO: test expirationProtected
    }

    /**
     * Test the property 'expires'
     */
    @Test
    public void expiresTest() {
        // TODO: test expires
    }

    /**
     * Test the property 'exposeWhois'
     */
    @Test
    public void exposeWhoisTest() {
        // TODO: test exposeWhois
    }

    /**
     * Test the property 'holdRegistrar'
     */
    @Test
    public void holdRegistrarTest() {
        // TODO: test holdRegistrar
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'nameServers'
     */
    @Test
    public void nameServersTest() {
        // TODO: test nameServers
    }

    /**
     * Test the property 'privacy'
     */
    @Test
    public void privacyTest() {
        // TODO: test privacy
    }

    /**
     * Test the property 'registrarCreatedAt'
     */
    @Test
    public void registrarCreatedAtTest() {
        // TODO: test registrarCreatedAt
    }

    /**
     * Test the property 'renewAuto'
     */
    @Test
    public void renewAutoTest() {
        // TODO: test renewAuto
    }

    /**
     * Test the property 'renewDeadline'
     */
    @Test
    public void renewDeadlineTest() {
        // TODO: test renewDeadline
    }

    /**
     * Test the property 'renewable'
     */
    @Test
    public void renewableTest() {
        // TODO: test renewable
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'transferAwayEligibleAt'
     */
    @Test
    public void transferAwayEligibleAtTest() {
        // TODO: test transferAwayEligibleAt
    }

    /**
     * Test the property 'transferProtected'
     */
    @Test
    public void transferProtectedTest() {
        // TODO: test transferProtected
    }

}
