/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ConsentDomainUpdate;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DomainUpdate
 */
public class DomainUpdateTest {
    private final DomainUpdate model = new DomainUpdate();

    /**
     * Model tests for DomainUpdate
     */
    @Test
    public void testDomainUpdate() {
        // TODO: test DomainUpdate
    }

    /**
     * Test the property 'consent'
     */
    @Test
    public void consentTest() {
        // TODO: test consent
    }

    /**
     * Test the property 'exposeWhois'
     */
    @Test
    public void exposeWhoisTest() {
        // TODO: test exposeWhois
    }

    /**
     * Test the property 'locked'
     */
    @Test
    public void lockedTest() {
        // TODO: test locked
    }

    /**
     * Test the property 'nameServers'
     */
    @Test
    public void nameServersTest() {
        // TODO: test nameServers
    }

    /**
     * Test the property 'renewAuto'
     */
    @Test
    public void renewAutoTest() {
        // TODO: test renewAuto
    }

    /**
     * Test the property 'subaccountId'
     */
    @Test
    public void subaccountIdTest() {
        // TODO: test subaccountId
    }

}
