/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.Consent;
import com.konfigthis.client.model.Contact;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DomainTransferIn
 */
public class DomainTransferInTest {
    private final DomainTransferIn model = new DomainTransferIn();

    /**
     * Model tests for DomainTransferIn
     */
    @Test
    public void testDomainTransferIn() {
        // TODO: test DomainTransferIn
    }

    /**
     * Test the property 'authCode'
     */
    @Test
    public void authCodeTest() {
        // TODO: test authCode
    }

    /**
     * Test the property 'consent'
     */
    @Test
    public void consentTest() {
        // TODO: test consent
    }

    /**
     * Test the property 'contactAdmin'
     */
    @Test
    public void contactAdminTest() {
        // TODO: test contactAdmin
    }

    /**
     * Test the property 'contactBilling'
     */
    @Test
    public void contactBillingTest() {
        // TODO: test contactBilling
    }

    /**
     * Test the property 'contactRegistrant'
     */
    @Test
    public void contactRegistrantTest() {
        // TODO: test contactRegistrant
    }

    /**
     * Test the property 'contactTech'
     */
    @Test
    public void contactTechTest() {
        // TODO: test contactTech
    }

    /**
     * Test the property 'period'
     */
    @Test
    public void periodTest() {
        // TODO: test period
    }

    /**
     * Test the property 'privacy'
     */
    @Test
    public void privacyTest() {
        // TODO: test privacy
    }

    /**
     * Test the property 'renewAuto'
     */
    @Test
    public void renewAutoTest() {
        // TODO: test renewAuto
    }

}
