/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ConsentRenew
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ConsentRenew {
  public static final String SERIALIZED_NAME_AGREED_AT = "agreedAt";
  @SerializedName(SERIALIZED_NAME_AGREED_AT)
  private String agreedAt;

  public static final String SERIALIZED_NAME_AGREED_BY = "agreedBy";
  @SerializedName(SERIALIZED_NAME_AGREED_BY)
  private String agreedBy;

  public static final String SERIALIZED_NAME_CURRENCY = "currency";
  @SerializedName(SERIALIZED_NAME_CURRENCY)
  private String currency = "USD";

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  private Integer price;

  public static final String SERIALIZED_NAME_REGISTRY_PREMIUM_PRICING = "registryPremiumPricing";
  @SerializedName(SERIALIZED_NAME_REGISTRY_PREMIUM_PRICING)
  private Boolean registryPremiumPricing;

  public ConsentRenew() {
  }

  public ConsentRenew agreedAt(String agreedAt) {
    
    
    
    
    this.agreedAt = agreedAt;
    return this;
  }

   /**
   * Timestamp indicating when the end-user consented to these legal agreements
   * @return agreedAt
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Timestamp indicating when the end-user consented to these legal agreements")

  public String getAgreedAt() {
    return agreedAt;
  }


  public void setAgreedAt(String agreedAt) {
    
    
    
    this.agreedAt = agreedAt;
  }


  public ConsentRenew agreedBy(String agreedBy) {
    
    
    
    
    this.agreedBy = agreedBy;
    return this;
  }

   /**
   * Originating client IP address of the end-user&#39;s computer when they consented to these legal agreements
   * @return agreedBy
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Originating client IP address of the end-user's computer when they consented to these legal agreements")

  public String getAgreedBy() {
    return agreedBy;
  }


  public void setAgreedBy(String agreedBy) {
    
    
    
    this.agreedBy = agreedBy;
  }


  public ConsentRenew currency(String currency) {
    
    
    
    
    this.currency = currency;
    return this;
  }

   /**
   * Currency in which the &#x60;price&#x60; is listed
   * @return currency
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(example = "USD", required = true, value = "Currency in which the `price` is listed")

  public String getCurrency() {
    return currency;
  }


  public void setCurrency(String currency) {
    
    
    
    this.currency = currency;
  }


  public ConsentRenew price(Integer price) {
    
    
    
    
    this.price = price;
    return this;
  }

   /**
   * Price of the domain excluding taxes or fees. Please use GET /v2/customers/{customerId}/domains/{domain} to retrieve the renewal price and currency for the domain
   * @return price
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Price of the domain excluding taxes or fees. Please use GET /v2/customers/{customerId}/domains/{domain} to retrieve the renewal price and currency for the domain")

  public Integer getPrice() {
    return price;
  }


  public void setPrice(Integer price) {
    
    
    
    this.price = price;
  }


  public ConsentRenew registryPremiumPricing(Boolean registryPremiumPricing) {
    
    
    
    
    this.registryPremiumPricing = registryPremiumPricing;
    return this;
  }

   /**
   * Only required for hosted registrar if domain is premium. If true indicates that the &#x60;price&#x60; and &#x60;currency&#x60; listed are the registry premium price and currency for the domain
   * @return registryPremiumPricing
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Only required for hosted registrar if domain is premium. If true indicates that the `price` and `currency` listed are the registry premium price and currency for the domain")

  public Boolean getRegistryPremiumPricing() {
    return registryPremiumPricing;
  }


  public void setRegistryPremiumPricing(Boolean registryPremiumPricing) {
    
    
    
    this.registryPremiumPricing = registryPremiumPricing;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ConsentRenew consentRenew = (ConsentRenew) o;
    return Objects.equals(this.agreedAt, consentRenew.agreedAt) &&
        Objects.equals(this.agreedBy, consentRenew.agreedBy) &&
        Objects.equals(this.currency, consentRenew.currency) &&
        Objects.equals(this.price, consentRenew.price) &&
        Objects.equals(this.registryPremiumPricing, consentRenew.registryPremiumPricing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(agreedAt, agreedBy, currency, price, registryPremiumPricing);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ConsentRenew {\n");
    sb.append("    agreedAt: ").append(toIndentedString(agreedAt)).append("\n");
    sb.append("    agreedBy: ").append(toIndentedString(agreedBy)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    registryPremiumPricing: ").append(toIndentedString(registryPremiumPricing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("agreedAt");
    openapiFields.add("agreedBy");
    openapiFields.add("currency");
    openapiFields.add("price");
    openapiFields.add("registryPremiumPricing");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("agreedAt");
    openapiRequiredFields.add("agreedBy");
    openapiRequiredFields.add("currency");
    openapiRequiredFields.add("price");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ConsentRenew
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ConsentRenew.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ConsentRenew is not found in the empty JSON string", ConsentRenew.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!ConsentRenew.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `ConsentRenew` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ConsentRenew.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("agreedAt").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `agreedAt` to be a primitive type in the JSON string but got `%s`", jsonObj.get("agreedAt").toString()));
      }
      if (!jsonObj.get("agreedBy").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `agreedBy` to be a primitive type in the JSON string but got `%s`", jsonObj.get("agreedBy").toString()));
      }
      if (!jsonObj.get("currency").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `currency` to be a primitive type in the JSON string but got `%s`", jsonObj.get("currency").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ConsentRenew.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ConsentRenew' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ConsentRenew> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ConsentRenew.class));

       return (TypeAdapter<T>) new TypeAdapter<ConsentRenew>() {
           @Override
           public void write(JsonWriter out, ConsentRenew value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ConsentRenew read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ConsentRenew given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ConsentRenew
  * @throws IOException if the JSON string is invalid with respect to ConsentRenew
  */
  public static ConsentRenew fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ConsentRenew.class);
  }

 /**
  * Convert an instance of ConsentRenew to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

