/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.ConsentV2;
import com.konfigthis.client.model.DomainContactsCreateV2;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DomainPurchaseV2
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DomainPurchaseV2 {
  public static final String SERIALIZED_NAME_CONSENT = "consent";
  @SerializedName(SERIALIZED_NAME_CONSENT)
  private ConsentV2 consent;

  public static final String SERIALIZED_NAME_CONTACTS = "contacts";
  @SerializedName(SERIALIZED_NAME_CONTACTS)
  private DomainContactsCreateV2 contacts;

  public static final String SERIALIZED_NAME_DOMAIN = "domain";
  @SerializedName(SERIALIZED_NAME_DOMAIN)
  private String domain;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Object metadata;

  public static final String SERIALIZED_NAME_NAME_SERVERS = "nameServers";
  @SerializedName(SERIALIZED_NAME_NAME_SERVERS)
  private List<String> nameServers = null;

  public static final String SERIALIZED_NAME_PERIOD = "period";
  @SerializedName(SERIALIZED_NAME_PERIOD)
  private Integer period = 1;

  public static final String SERIALIZED_NAME_PRIVACY = "privacy";
  @SerializedName(SERIALIZED_NAME_PRIVACY)
  private Boolean privacy = false;

  public static final String SERIALIZED_NAME_RENEW_AUTO = "renewAuto";
  @SerializedName(SERIALIZED_NAME_RENEW_AUTO)
  private Boolean renewAuto = true;

  public DomainPurchaseV2() {
  }

  public DomainPurchaseV2 consent(ConsentV2 consent) {
    
    
    
    
    this.consent = consent;
    return this;
  }

   /**
   * Get consent
   * @return consent
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public ConsentV2 getConsent() {
    return consent;
  }


  public void setConsent(ConsentV2 consent) {
    
    
    
    this.consent = consent;
  }


  public DomainPurchaseV2 contacts(DomainContactsCreateV2 contacts) {
    
    
    
    
    this.contacts = contacts;
    return this;
  }

   /**
   * Get contacts
   * @return contacts
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public DomainContactsCreateV2 getContacts() {
    return contacts;
  }


  public void setContacts(DomainContactsCreateV2 contacts) {
    
    
    
    this.contacts = contacts;
  }


  public DomainPurchaseV2 domain(String domain) {
    
    
    
    
    this.domain = domain;
    return this;
  }

   /**
   * For internationalized domain names with non-ascii characters, the domain name is converted to punycode before format and pattern validation rules are checked
   * @return domain
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "For internationalized domain names with non-ascii characters, the domain name is converted to punycode before format and pattern validation rules are checked")

  public String getDomain() {
    return domain;
  }


  public void setDomain(String domain) {
    
    
    
    this.domain = domain;
  }


  public DomainPurchaseV2 metadata(Object metadata) {
    
    
    
    
    this.metadata = metadata;
    return this;
  }

   /**
   * The domain eligibility data fields as specified by GET /v2/customers/{customerId}/domains/register/schema/{tld}
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The domain eligibility data fields as specified by GET /v2/customers/{customerId}/domains/register/schema/{tld}")

  public Object getMetadata() {
    return metadata;
  }


  public void setMetadata(Object metadata) {
    
    
    
    this.metadata = metadata;
  }


  public DomainPurchaseV2 nameServers(List<String> nameServers) {
    
    
    
    
    this.nameServers = nameServers;
    return this;
  }

  public DomainPurchaseV2 addNameServersItem(String nameServersItem) {
    if (this.nameServers == null) {
      this.nameServers = new ArrayList<>();
    }
    this.nameServers.add(nameServersItem);
    return this;
  }

   /**
   * Get nameServers
   * @return nameServers
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getNameServers() {
    return nameServers;
  }


  public void setNameServers(List<String> nameServers) {
    
    
    
    this.nameServers = nameServers;
  }


  public DomainPurchaseV2 period(Integer period) {
    if (period != null && period < 1) {
      throw new IllegalArgumentException("Invalid value for period. Must be greater than or equal to 1.");
    }
    if (period != null && period > 10) {
      throw new IllegalArgumentException("Invalid value for period. Must be less than or equal to 10.");
    }
    
    
    this.period = period;
    return this;
  }

   /**
   * Get period
   * minimum: 1
   * maximum: 10
   * @return period
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "1", value = "")

  public Integer getPeriod() {
    return period;
  }


  public void setPeriod(Integer period) {
    if (period != null && period < 1) {
      throw new IllegalArgumentException("Invalid value for period. Must be greater than or equal to 1.");
    }
    if (period != null && period > 10) {
      throw new IllegalArgumentException("Invalid value for period. Must be less than or equal to 10.");
    }
    
    this.period = period;
  }


  public DomainPurchaseV2 privacy(Boolean privacy) {
    
    
    
    
    this.privacy = privacy;
    return this;
  }

   /**
   * Get privacy
   * @return privacy
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "false", value = "")

  public Boolean getPrivacy() {
    return privacy;
  }


  public void setPrivacy(Boolean privacy) {
    
    
    
    this.privacy = privacy;
  }


  public DomainPurchaseV2 renewAuto(Boolean renewAuto) {
    
    
    
    
    this.renewAuto = renewAuto;
    return this;
  }

   /**
   * Get renewAuto
   * @return renewAuto
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "true", value = "")

  public Boolean getRenewAuto() {
    return renewAuto;
  }


  public void setRenewAuto(Boolean renewAuto) {
    
    
    
    this.renewAuto = renewAuto;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DomainPurchaseV2 domainPurchaseV2 = (DomainPurchaseV2) o;
    return Objects.equals(this.consent, domainPurchaseV2.consent) &&
        Objects.equals(this.contacts, domainPurchaseV2.contacts) &&
        Objects.equals(this.domain, domainPurchaseV2.domain) &&
        Objects.equals(this.metadata, domainPurchaseV2.metadata) &&
        Objects.equals(this.nameServers, domainPurchaseV2.nameServers) &&
        Objects.equals(this.period, domainPurchaseV2.period) &&
        Objects.equals(this.privacy, domainPurchaseV2.privacy) &&
        Objects.equals(this.renewAuto, domainPurchaseV2.renewAuto);
  }

  @Override
  public int hashCode() {
    return Objects.hash(consent, contacts, domain, metadata, nameServers, period, privacy, renewAuto);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DomainPurchaseV2 {\n");
    sb.append("    consent: ").append(toIndentedString(consent)).append("\n");
    sb.append("    contacts: ").append(toIndentedString(contacts)).append("\n");
    sb.append("    domain: ").append(toIndentedString(domain)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    nameServers: ").append(toIndentedString(nameServers)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    privacy: ").append(toIndentedString(privacy)).append("\n");
    sb.append("    renewAuto: ").append(toIndentedString(renewAuto)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("consent");
    openapiFields.add("contacts");
    openapiFields.add("domain");
    openapiFields.add("metadata");
    openapiFields.add("nameServers");
    openapiFields.add("period");
    openapiFields.add("privacy");
    openapiFields.add("renewAuto");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("consent");
    openapiRequiredFields.add("domain");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DomainPurchaseV2
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DomainPurchaseV2.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DomainPurchaseV2 is not found in the empty JSON string", DomainPurchaseV2.openapiRequiredFields.toString()));
        }
      }

      Set<Entry<String, JsonElement>> entries = jsonObj.entrySet();
      // check to see if the JSON string contains additional fields
      for (Entry<String, JsonElement> entry : entries) {
        if (!DomainPurchaseV2.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `DomainPurchaseV2` properties. JSON: %s", entry.getKey(), jsonObj.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : DomainPurchaseV2.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      // validate the required field `consent`
      ConsentV2.validateJsonObject(jsonObj.getAsJsonObject("consent"));
      // validate the optional field `contacts`
      if (jsonObj.get("contacts") != null && !jsonObj.get("contacts").isJsonNull()) {
        DomainContactsCreateV2.validateJsonObject(jsonObj.getAsJsonObject("contacts"));
      }
      if (!jsonObj.get("domain").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `domain` to be a primitive type in the JSON string but got `%s`", jsonObj.get("domain").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("nameServers") != null && !jsonObj.get("nameServers").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `nameServers` to be an array in the JSON string but got `%s`", jsonObj.get("nameServers").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DomainPurchaseV2.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DomainPurchaseV2' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DomainPurchaseV2> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DomainPurchaseV2.class));

       return (TypeAdapter<T>) new TypeAdapter<DomainPurchaseV2>() {
           @Override
           public void write(JsonWriter out, DomainPurchaseV2 value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public DomainPurchaseV2 read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             return thisAdapter.fromJsonTree(jsonObj);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DomainPurchaseV2 given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DomainPurchaseV2
  * @throws IOException if the JSON string is invalid with respect to DomainPurchaseV2
  */
  public static DomainPurchaseV2 fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DomainPurchaseV2.class);
  }

 /**
  * Convert an instance of DomainPurchaseV2 to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

