/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * ErrorFieldDomainContactsValidate
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class ErrorFieldDomainContactsValidate {
  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private String code;

  public static final String SERIALIZED_NAME_DOMAINS = "domains";
  @SerializedName(SERIALIZED_NAME_DOMAINS)
  private List<String> domains = new ArrayList<>();

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_PATH_RELATED = "pathRelated";
  @SerializedName(SERIALIZED_NAME_PATH_RELATED)
  private String pathRelated;

  public ErrorFieldDomainContactsValidate() {
  }

  public ErrorFieldDomainContactsValidate code(String code) {
    
    
    
    
    this.code = code;
    return this;
  }

   /**
   * Short identifier for the error, suitable for indicating the specific error within client code
   * @return code
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "Short identifier for the error, suitable for indicating the specific error within client code")

  public String getCode() {
    return code;
  }


  public void setCode(String code) {
    
    
    
    this.code = code;
  }


  public ErrorFieldDomainContactsValidate domains(List<String> domains) {
    
    
    
    
    this.domains = domains;
    return this;
  }

  public ErrorFieldDomainContactsValidate addDomainsItem(String domainsItem) {
    this.domains.add(domainsItem);
    return this;
  }

   /**
   * An array of domain names the error is for. If tlds are specified in the request, &#x60;domains&#x60; will contain tlds. For example, if &#x60;domains&#x60; in request is [\&quot;test1.com\&quot;, \&quot;test2.uk\&quot;, \&quot;net\&quot;], and the field is invalid for com and net, then one of the &#x60;fields&#x60; in response will have [\&quot;test1.com\&quot;, \&quot;net\&quot;] as &#x60;domains&#x60;
   * @return domains
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "An array of domain names the error is for. If tlds are specified in the request, `domains` will contain tlds. For example, if `domains` in request is [\"test1.com\", \"test2.uk\", \"net\"], and the field is invalid for com and net, then one of the `fields` in response will have [\"test1.com\", \"net\"] as `domains`")

  public List<String> getDomains() {
    return domains;
  }


  public void setDomains(List<String> domains) {
    
    
    
    this.domains = domains;
  }


  public ErrorFieldDomainContactsValidate message(String message) {
    
    
    
    
    this.message = message;
    return this;
  }

   /**
   * Human-readable, English description of the problem with the contents of the field
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Human-readable, English description of the problem with the contents of the field")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    
    
    
    this.message = message;
  }


  public ErrorFieldDomainContactsValidate path(String path) {
    
    
    
    
    this.path = path;
    return this;
  }

   /**
   * 1) JSONPath referring to the field within the data containing an error&lt;br/&gt;or&lt;br/&gt;2) JSONPath referring to an object containing an error
   * @return path
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "1) JSONPath referring to the field within the data containing an error<br/>or<br/>2) JSONPath referring to an object containing an error")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    
    
    
    this.path = path;
  }


  public ErrorFieldDomainContactsValidate pathRelated(String pathRelated) {
    
    
    
    
    this.pathRelated = pathRelated;
    return this;
  }

   /**
   * JSONPath referring to the field on the object referenced by &#x60;path&#x60; containing an error
   * @return pathRelated
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "JSONPath referring to the field on the object referenced by `path` containing an error")

  public String getPathRelated() {
    return pathRelated;
  }


  public void setPathRelated(String pathRelated) {
    
    
    
    this.pathRelated = pathRelated;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the ErrorFieldDomainContactsValidate instance itself
   */
  public ErrorFieldDomainContactsValidate putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ErrorFieldDomainContactsValidate errorFieldDomainContactsValidate = (ErrorFieldDomainContactsValidate) o;
    return Objects.equals(this.code, errorFieldDomainContactsValidate.code) &&
        Objects.equals(this.domains, errorFieldDomainContactsValidate.domains) &&
        Objects.equals(this.message, errorFieldDomainContactsValidate.message) &&
        Objects.equals(this.path, errorFieldDomainContactsValidate.path) &&
        Objects.equals(this.pathRelated, errorFieldDomainContactsValidate.pathRelated)&&
        Objects.equals(this.additionalProperties, errorFieldDomainContactsValidate.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(code, domains, message, path, pathRelated, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ErrorFieldDomainContactsValidate {\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    domains: ").append(toIndentedString(domains)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    pathRelated: ").append(toIndentedString(pathRelated)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("code");
    openapiFields.add("domains");
    openapiFields.add("message");
    openapiFields.add("path");
    openapiFields.add("pathRelated");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
    openapiRequiredFields.add("code");
    openapiRequiredFields.add("domains");
    openapiRequiredFields.add("path");
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to ErrorFieldDomainContactsValidate
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!ErrorFieldDomainContactsValidate.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in ErrorFieldDomainContactsValidate is not found in the empty JSON string", ErrorFieldDomainContactsValidate.openapiRequiredFields.toString()));
        }
      }

      // check to make sure all required properties/fields are present in the JSON string
      for (String requiredField : ErrorFieldDomainContactsValidate.openapiRequiredFields) {
        if (jsonObj.get(requiredField) == null) {
          throw new IllegalArgumentException(String.format("The required field `%s` is not found in the JSON string: %s", requiredField, jsonObj.toString()));
        }
      }
      if (!jsonObj.get("code").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `code` to be a primitive type in the JSON string but got `%s`", jsonObj.get("code").toString()));
      }
      // ensure the required json array is present
      if (jsonObj.get("domains") == null) {
        throw new IllegalArgumentException("Expected the field `linkedContent` to be an array in the JSON string but got `null`");
      } else if (!jsonObj.get("domains").isJsonArray()) {
        throw new IllegalArgumentException(String.format("Expected the field `domains` to be an array in the JSON string but got `%s`", jsonObj.get("domains").toString()));
      }
      if ((jsonObj.get("message") != null && !jsonObj.get("message").isJsonNull()) && !jsonObj.get("message").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `message` to be a primitive type in the JSON string but got `%s`", jsonObj.get("message").toString()));
      }
      if (!jsonObj.get("path").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `path` to be a primitive type in the JSON string but got `%s`", jsonObj.get("path").toString()));
      }
      if ((jsonObj.get("pathRelated") != null && !jsonObj.get("pathRelated").isJsonNull()) && !jsonObj.get("pathRelated").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `pathRelated` to be a primitive type in the JSON string but got `%s`", jsonObj.get("pathRelated").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ErrorFieldDomainContactsValidate.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ErrorFieldDomainContactsValidate' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ErrorFieldDomainContactsValidate> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ErrorFieldDomainContactsValidate.class));

       return (TypeAdapter<T>) new TypeAdapter<ErrorFieldDomainContactsValidate>() {
           @Override
           public void write(JsonWriter out, ErrorFieldDomainContactsValidate value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public ErrorFieldDomainContactsValidate read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             ErrorFieldDomainContactsValidate instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of ErrorFieldDomainContactsValidate given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of ErrorFieldDomainContactsValidate
  * @throws IOException if the JSON string is invalid with respect to ErrorFieldDomainContactsValidate
  */
  public static ErrorFieldDomainContactsValidate fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ErrorFieldDomainContactsValidate.class);
  }

 /**
  * Convert an instance of ErrorFieldDomainContactsValidate to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

