/*
 * 
 * All the help and tools you need to grow online: Websites, Domains, Digital and Social Marketing - plus GoDaddy Guides with you every step of the way.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.api;

import com.konfigthis.client.ApiException;
import com.konfigthis.client.ApiClient;
import com.konfigthis.client.ApiException;
import com.konfigthis.client.Configuration;
import com.konfigthis.client.model.Action;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.BeforeAll;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ActionsApi
 */
@Disabled
public class ActionsApiTest {

    private static ActionsApi api;

    
    @BeforeAll
    public static void beforeClass() {
        ApiClient apiClient = Configuration.getDefaultApiClient();
        api = new ActionsApi(apiClient);
    }

    /**
     * Cancel the most recent user action for the specified domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void cancelRecentActionTest() throws ApiException {
        String customerId = null;
        String domain = null;
        String type = null;
        String xRequestId = null;
        api.cancelRecentAction(customerId, domain, type)
                .xRequestId(xRequestId)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieves the most recent action for the specified domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRecentActionTest() throws ApiException {
        String customerId = null;
        String domain = null;
        String type = null;
        String xRequestId = null;
        Action response = api.getRecentAction(customerId, domain, type)
                .xRequestId(xRequestId)
                .execute();
        // TODO: test validations
    }

    /**
     * Retrieves a list of the most recent actions for the specified domain
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getRecentListTest() throws ApiException {
        String customerId = null;
        String domain = null;
        String xRequestId = null;
        List<Action> response = api.getRecentList(customerId, domain)
                .xRequestId(xRequestId)
                .execute();
        // TODO: test validations
    }

}
